### ISSUE TITLE
unexpect backspace behavior when active region.

### ISSUE THREAD

**Issue by zw963** [mattfidler/auto-indent-mode.el#45]
e.g:

```cl
(eval-after-load "cus-load"
  '(progn (custom-add-load 'data 'session)
         | (custom-add-load 'session 'session)))
```

point is before second `(custom-add-load`.

1.  run `mark-sexp` to mark `(custom-add-load 'session 'session)`
2.  press backspace

What i expect is
```cl
(eval-after-load "cus-load"
  '(progn (custom-add-load 'data 'session)
          ))
```

But, result is:
```cl
(eval-after-load "cus-load"
  '(progn (custom-add-load 'data 'session)(custom-add-load 'session 'session)))

```

Thanks.

**Comment by mattfidler** [comment]
Thanks for the report.   I will look into it within the next week.

**Comment by zw963** [comment]
Another relative problem:

```cl
(add-list-to-list
 'ido-ignore-buffers
 '("\\` " "^\*Back" "^\*Selection" ".*Comp" "^\*Ido" "^\*trace" "^\*scratch\*"
   "^\*compilation" "^\*GTAGS" "^session\.*" "Scratch.txt")
 )
```

mark ``"\\` "`` as region, backspace, result:
```el
(add-list-to-list
 'ido-ignore-buffers
 ' "^\*Back" "^\*Selection" ".*Comp" "^\*Ido" "^\*trace" "^\*scratch\*"
   "^\*compilation" "^\*GTAGS" "^session\.*" "Scratch.txt")
 )

```

**Comment by mattfidler** [comment]
This now works for me.  Hopefully it works for you :)

**Comment by zw963** [comment]
Second problem fixed.

But, the first problem (Topic) is still not fixed for me?

Emacs 24.5.

**Comment by mattfidler** [comment]
Hm.  When I tested it it worked fine. Did you press backspace or C-d?

**Comment by zw963** [comment]
Backspace,  I expect behavior is only remove region, not delete back
to previous line, But, it always delete to previous line.

following is a gif

http://zw963.github.io/recorded2302714.gif

**Comment by mattfidler** [comment]
Thanks.  I will see what I can do

**Comment by mattfidler** [comment]
I cannot reproduce your issue any longer.

**Comment by mattfidler** [comment]
I provided a different method to fix the issue.  Let me know if it works for you.  (It works for me again).

**Comment by zw963** [comment]
> I provided a different method to fix the issue. Let me know if it works for you. (It works for me again).

It fixed, thanks.

though, I don't know why you could not reproduce my case?

**Comment by mattfidler** [comment]
Not sure.  i could reproduce your case, but when fixing it the first time, I could not.

**Comment by mattfidler** [comment]
I have found this happens to me from time to time :(

**Comment by zw963** [comment]
> I have found this happens to me from time to time :(

before a create a issue, I will test with just keep only needed package config in my dotfiles.

e.g. 

```cl
(add-to-list 'load-path "....")
(require 'package)
(open-package-mode)
(error "Done") ; code stop execute here

 ...  ;; my dotfiles
```

this prevent any potential impact. which could cause some unexpected behavior.
