### ISSUE TITLE
c-basic-offset is not respected

### ISSUE THREAD

**Issue by nordlow** [mattfidler/auto-indent-mode.el#51]
`c-basic-offset` is not respected by `auto-indent-mode`.

The docs at https://www.emacswiki.org/emacs/AutoIndentMode are very strange. Specifically the phrase

_Looking to see if major mode variables major-mode-indent-level and major-mode-basic-offset variables are present. If either of these variables are present, auto-indent-mode sets these variables to the default auto-indent-assign-indent-level._

seems opposite of what you want.

Instead I want `auto-indent-mode` to by default respect `c-basic-offset` unless a specific configuration was made.

If I set `auto-indent-assign-indent-level` to `nil` I get zero offset which is never a desired behaviour.

**Comment by mattfidler** [comment]
Forgive the delayed response.  

I personally like to set my offset level once, and have all the languages respect that choice.  I respect your preference is different.

Before, you could have suppressed this by
```
(setq auto-indent-assign-indent-level-variables nil)
```
However, you can now also use what you seemed to have already tried:
```
(setq auto-indent-assign-indent-level nil)
```
