### ISSUE TITLE
auto-indent-whole-buffer doesn't seem to do anything

### ISSUE THREAD

**Issue by Saikyun** [mattfidler/auto-indent-mode.el#54]
When having misaligned code, e.g.:

```
    public void clear() {
        hasPressedEnter = false;
        stringToEdit = "";
        fieldIsActive = false;
}
```

auto-indent-whole-buffer doesn't fix it. I've also activated auto indent on save and visit, and those doesn't seem to fix it either.

**Comment by mattfidler** [comment]
`auto-indent-whole-buffer` simply runs `(indent-region (point-min) (point-max))`.  I think this is a parsing/mode error.  In theory `(indent-region (point-min) (point-max))` should do the trick in any mode.

**Comment by mattfidler** [comment]
The other two things that it does is `tabify` or `untabify` based on the setting `auto-indent-untabify-on-visit-file`.   You could try setting this to `nil` to see if that works...

```lisp
(setq auto-indent-untabify-on-visit-file nil)
```

**Comment by Saikyun** [comment]
`(indent-region (point-min) (point-max))` works but `M-x auto-indent-whole-buffer` doesn't...

**Comment by Saikyun** [comment]
The modes I'm using are C#, ARev, omnisharp, FlyC, LR, AI, company and helm, if that matters. I guess I could try turning the minor modes off and see if there's any difference.

**Comment by Saikyun** [comment]
Same result with just C# and AI activated.

**Comment by mattfidler** [comment]
Are you in a repository (say a github repository for instance)?  

If so, the command will not work since the auto-indent-style is 'moderate.  This means, to prevent auto-indent from changing other repositories' indentation rules, auto-indent will back out of indentation.

You can test this by setting:

```lisp
(setq auto-indent-indent-style 'aggressive)
```

and see if it works.

**Comment by Saikyun** [comment]
I am! That did the trick, thanks! I must've misread the documentation, I thought aggressive was the default. :)

**Comment by mattfidler** [comment]
Great!
