### ISSUE TITLE
auto-indent-home-is-beginning-of-indent not activated for visual-line-mode

### ISSUE THREAD

**Issue by laurynas-biveinis** [mattfidler/auto-indent-mode.el#61]
C-a / Home is advised for `move-beginning-for-line`. However, with visual-line-mode enabled, that one is never called for these keys, and `beginning-of-visual-line` is called instead. This results in C-a always going to the first column, ignoring `auto-indent-home-is-beginning-of-indent` setting.

This is workaroundable in .emacs by
```lisp
(advice-add 'beginning-of-visual-line :around #'ad-Advice-move-beginning-of-line)
```

**Comment by mattfidler** [comment]
I'm unsure if this will work too.  In theory it adds the advice.

Can you check if it works for you.

**Comment by laurynas-biveinis** [comment]
Thank you @mattfidler - I get `error: ad-enable-advice: ‘beginning-of-visual-line’ is not advised` with the patch

**Comment by mattfidler** [comment]
I just directly added the advice.  Hopefully there isn't an unseen consequence.

**Comment by laurynas-biveinis** [comment]
Confirmed the fix, thank you

**Comment by mattfidler** [comment]
Great

**Comment by jeffvalk** [comment]
The patch applied in e6da518 seems to break interoperability with `company`. Here's a minimal example to reproduce:

```sh
emacs -Q
```

Then in `*scratch*`:

```elisp
(require 'package)
(package-initialize)

(require 'auto-indent-mode)
(require 'company)
(company-mode)
```

After this, type anything that would trigger elisp auto-completion. This causes the following error:

```
Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Symbol’s function definition is void: ad-Advice-move-beginning-of-line" on command post-command
```

Removing the advice introduced by e6da518 stops the errors and allows completion using `company` to work again:
```elisp
(advice-remove 'beginning-of-visual-line #'ad-Advice-move-beginning-of-line)
```
