### ISSUE TITLE
Line break causes an error when loading the package

### ISSUE THREAD

**Issue by rockneurotiko** [mattfidler/auto-indent-mode.el#63]
In the last commit (https://github.com/mattfidler/auto-indent-mode.el/commit/8dffa08ab631bf9c388d076958f4da735eaa3e3a) a line break was introduced in auto-indent-mode.el:2646:

``` elisp
(add-hook 'after-change-
	  major-mode-hook 'auto-indent-disable-electric)
```

This causes an error when loading the package:

`auto-indent-mode/:catch: Symbol’s value as variable is void: major-mode-hook`

**Comment by laurynas-biveinis** [comment]
Seems like a regression from the preliminary fix for https://github.com/mattfidler/auto-indent-mode.el/issues/62
